---
- name: Updating cache and installing systemd and unzip
  apt:
    update_cache: yes
    name: ['unzip', 'systemd']
    state: present
  register: task_result
  until: task_result is succeeded
  retries: 5
  delay: 5

- name: Creating user for prometheus
  user:
   name: prometheus
   shell: /bin/false

- name: Setting internal variables for convinience
  set_fact:
    prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

- name: Downloading the binary file for Prometheus
  unarchive:
    src: "{{ prometheus_url }}"
    dest: /tmp/
    remote_src: yes

- name: Move the binary executable file
  copy:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus
    dest: /usr/local/bin/
    mode: 0555
    remote_src: yes

- name: Create directory for Prometheus Configuration and for Data dump
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Adding Prometheus Configuration
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: Copy Service for Prometheus
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - reload_prometheus_service
    - restart_prometheus_service
